name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci # Instala as dependências do projeto sem perguntar ou alterar o package.json
        env:
          DATABASE_URL: "postgresql://fake:fake@localhost:5432/fake?schema=public"

      - run: npm run test